name: Daily Request Script

on:
  schedule:
    # Run daily at midnight UTC
    - cron: '0 0 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install uv
      run: |
        if ! command -v uv >/dev/null 2>&1; then
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        else
          echo "uv is already installed"
        fi
        
    - name: Install dependencies
      run: uv sync --no-dev
        
    - name: Run Python script
      env:
        MIKEY_SECRET: ${{ secrets.MIKEY_SECRET }}
      run: uv run python scripts/daily_request.py
      
    - name: Upload response file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: response-file
        path: response.txt 